### ISSUE TITLE
Still manipulates class names

### ISSUE THREAD

**Issue by filipstefansson** [scherebedov/postcss-global-import#1]
It works well in most cases, but it seems like some class names inside media queries still gets affected.

I have a case where the class name inside node_modules is `.Grid__col--sm-4_1H-V_` but when I look at the class name after it's processed with PostCSS it's `.Grid__col--sm-4_1H-V_-1lIaV`.

My `localIdentName` for css modules is `[local]-[hash:base64:5]` so it seem that the hash is still added to the end.

I import the files like this:
`@global-import 'a_node_modules_package/Grid.css';`

I'm using react-starter-kit and import the file from a components CSS.

**Comment by Chaptykov** [comment]
What is node module which you used? Would you show your webpack configuration?

**Comment by JavoByte** [comment]
I imported [milligram](http://milligram.io/) which basic css works fine with global import. However, code inside `@media` are still manipulated.

This happens in my [react boilerplate](https://github.com/JavoByte/react-boilerplate)
